### PR TITLE
New character: Brunhilde, the Bone Witch

### PR DESCRIPTION
**Pull request by interfector**
This is a new character, another Folk Witch, I love them. Along with a minor fix to Rojyar with the virtues/flaws template.

### CODE REVIEW

**Comment by GuillaumeDIDIER** [comment]
It'd be simpler for me if you could split those changes into two commits or even two PR, making it easier to merge while keeping a clean history.

**Comment by GuillaumeDIDIER** [comment]
Aside from that little annoyance, it seems good to me. If you can rewrite it as two commits, it would be perfect.

**Comment by interfector** [comment]
I can try...I don't really know how except deleting the branch and recreating a new one.

**Comment by GuillaumeDIDIER** [comment]
`git reset` is a powerful multifunction but dangerous tool that could help achieve the split locally, or you can create a new local branch, and re-apply the changes there (by copying the file over from a backup directory for instance). In some cases `git add -p` can also help select which change to include in which commit.

Once you have a local branch, you could use `git push --force origin branch:brunhilde` to overwrite the PR content, and it would work.

**Pull request closed without merging**
