### PR TITLE
Sofia, at Gauntlet and 15 years after.

### PR DESCRIPTION
**Pull request by interfector**
This is Sofia, a dream witch. I could probably age her at +30 and +45 years after gauntlet.

### CODE REVIEW

**Comment by GuillaumeDIDIER** [comment]
Nice character. I've checked the rendering of the markdown, and there are a few subpar things, you can see that on the webpage https://github.com/interfector/Ars-Magica-Characters/blob/sofia/Magi/Sofia%20of%20Criamon/Sofia%2C%20the%20Dream%20Witch.md

- The sections appear weird, I'd say you need to add an extra newline before any new title, also no need to add extra # after the title, I think.
- There appear to be some weird boxes or something like that after stuff like age and size. I believe it has to do with the lines :
```
` `
```
These line should probably just be empty.

There are also a few tweaks I'd do to the spell formatting to make it clearer.
This is the markdown code I'd use:
```
**CrIg 10**

**R**: Touch, **D**: Conc, **T**: Ind

A flame leaps up in your palm, which must be upturned for the spell’s duration. The flame
casts light like a torch, and can ignite very flammable items. It does no damage, and
does not burn the caster.

*(Base 3, +1 Touch, +1 Conc)**
```
rendering like this:

**CrIg 10**

**R**: Touch, **D**: Conc, **T**: Ind

A flame leaps up in your palm, which must be upturned for the spell’s duration. The flame
casts light like a torch, and can ignite very flammable items. It does no damage, and
does not burn the caster.

*(Base 3, +1 Touch, +1 Conc)**

Optionally I could drop you the template we use to format xp + level of abilities and arts, but that's not necessary.

**Comment by interfector** [comment]
Well, that's really odd. I used Okular to preview the Markdown and I used the lines
` ` ` `
because adding a newline created a new paragraph and I hate the distance between the two lines.
This probably breaks because Github uses that to insert code blocks.
I'll add your few tweaks to the spell section.

**Comment by interfector** [comment]
Nevermind, I found how to do it. I need to insert two blankspaces at the end of the previous lines. I'll modify and recommit.

**Comment by GuillaumeDIDIER** [comment]
Pretty nice, I'll merge this

**Pull request merged**
