### PR TITLE
Sofia and Matilde

### PR DESCRIPTION
**Pull request by interfector**
I've created new stage for Sofia (+30 and +45) and then I created Matilde, a Folk Witch with various stages and new things.

### CODE REVIEW

**Comment by interfector** [comment]
I found that I need to do some minor fixed on Matilde, tomorrow I'll do it and, if it's all okay, you can merge it.

**Comment by GuillaumeDIDIER** [comment]
Is Mathilde forbidden from having long free hair or mist she have long free hairs ? (Just checking that you meant the former with Restriction, not the latter (which would be a Necessary condition))

**Comment by interfector** [comment]
It should be a Restriction, at least I thought it this way: Matilde should have long free hair to cast, she can't cast if she has shoer or collected hair.

Maybe Restriction (no short or collected hair) ?

**Comment by GuillaumeDIDIER** [comment]
> NECESSARY CONDITION
> Major, Hermetic
> In order for your magic to work, you must perform a specific action while casting any spell. This should be something simple, such as singing or spinning around three times. If you cannot perform the action, you cannot cast spells at all.

> RESTRICTION
> Major, Hermetic
> You cannot cast spells at all under certain uncommon conditions. These might refer to your state, such as touching the earth directly or having no beard, or to the target, such as birds or glass, or to your location when you use the magic, such as on a small boat or in a storm. The Restriction also applies to effects generated by any enchanted items you create. Spells cast remain in effect even if the Restriction comes into play. Thus, if your Restriction is that you must not have a beard, you cast a spell with Year duration, and then grow a beard, the spell does not fail.

Given those two description, I'd say Necessary Condition (long free hair) rather than Restriction (no long free hairs), but the best thing is to develop the meaning of the flaw precisely : *She must have her hair long and free for her to make use of magic. Cut her hair or tie them, and she is powerless.*

**Comment by interfector** [comment]
Yes, the meaning is exactly what you wrote. Given the description Necessary Condition seems more about an action to be done as you cast while Restriction seems a state you are in.

I'll switch to Necessary Condition and specify it in description.

**Comment by interfector** [comment]
I think I fixed everything I did wrong, there might be some minor errors but I didn't find them.

**Comment by GuillaumeDIDIER** [comment]
Would you mind double checking if the merge proceeded correctly, I got a weird error message from GitHub (but the merge proceeded).
(Check if your latest tweaks appear on the repo).

**Comment by interfector** [comment]
All should be good!

**Pull request merged**
