### PR TITLE
Create Fatorum the Parisian Holy Magus

### PR DESCRIPTION
**Pull request by MechanicusExRhine**
Someone help me with formatting. 

Signed: Fidelis from the Ars Magica Discord Server (In case the Holy Magus didn't give it away)

### CODE REVIEW

**Comment by GuillaumeDIDIER** [comment]
Good job, just a few nitpicks. Could you renamed the file to have the .md extension ?

Could you also please add the details of what his death prophecy is.

**Comment by GuillaumeDIDIER** [comment]
Skilled parent twice ??

**Comment by GuillaumeDIDIER** [comment]
Probably a Typo but the Qik value is missing.

**Comment by GuillaumeDIDIER** [comment]
Line 58, missing a space after Guile

**Comment by interfector** [comment]
I don't know if it is a problem on my part (maybe some configuration) but I see almost all the lines without new lines...

To fix this, it's enough to insert a double space after the end of a line and it should render as a new line.

**Comment by MechanicusExRhine** [comment]
Back, I added spaces at the end of each line as instructed, and added the missing Quickness score!
Is there anything else that needs fixing?

**Comment by GuillaumeDIDIER** [comment]
The characteristics point don't add up to 7 it seems, but only 6

**Comment by GuillaumeDIDIER** [comment]
~~Which house is he from, he seems to lack his free house virtue.~~

It needs to be stated somewhere he is from house Ex misc.

I usually format Virtues and Flaws as `**Name** *(minor, hermetic)*`

**Comment by GuillaumeDIDIER** [comment]
It seems like you forgot to specify the mastery level(s) for the Evening bell tolls for the accursed.

**Comment by MechanicusExRhine** [comment]
Added the missing Characteristic level, Mastery Score, and House (Just above characteristics). And adding the kind of Virtues right now.

**Comment by MechanicusExRhine** [comment]
And now it "should" be completely fixed, you may check it at your convenience.

**Pull request merged**
